spring:
  application:
    name: kgr-reservation-system
  jackson:
    default-property-inclusion: non_empty
  datasource:
    url: jdbc:mariadb://localhost:3306/reservationdb?useSSL=false&useCompression=true&assureReadOnly=true&socketTimeout=100000&rewriteBatchedStatements=true
    username: root
    password: mypass
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

server:
  shutdown: graceful
  port: 10001
  servlet:
    context-path: /kgr-reservation-system